name: Bug Report
description: Create a report to help the developer find existing issues in the code.
labels: [bug]
body:
    - type: textarea
      attributes:
          label: What steps will reproduce the problem?
          placeholder: |
              1.
              2.
              3.
      validations:
          required: true
    - type: textarea
      attributes:
          label: What is the expected output?
          description: What you expected to see.
      validations:
          required: true
    - type: textarea
      attributes:
          label: CustomFishing Version
          description: Do not say "latest". Output of the "/version CustomFishing" command.
      validations:
          required: true
    - type: textarea
      attributes:
          label: Server Version
          description: The server version you are currently running. Do not say "latest". Output of the "/version" command.
      validations:
          required: true
    - type: textarea
      attributes:
          label: Please use any paste site to link the required files. (paste.gg / pastebin.com / hastebin.com)
          description: This is a must, especially if the issue might have been caused by a misconfiguration.
          value: |
              1. Your full server startup from the logs\latest.log:
              2. Your CommandItems config.yml:

              (optional)
              3. The error that appears in console:
      validations:
          required: true
